### ISSUE TITLE
maaaybe thats too much automation :woman_dancing: 

### ISSUE THREAD

**Issue by ctubio** [erichlotto/yieldly-compounder#4]
:gift: 

:koala: just a little suggestion! (cos the rest of the code is awesome'¡)

consider asking to the user everytime MYALGO_PASSWORD with `readline` instead of hardcoding it
(and clean the screen with `console.clear()` or `process.stdout.write('\033c');` after reading it)

in that case, the script cannot be run by crontab, but need to be executed by users before go to zZzzzz, and you can setup the cron instead with [node-cron](https://www.npmjs.com/package/node-cron)

this way users still need to write their password before approving any transaction (that is what is supposed to happen; instead of risking having secrets on online computers) and still let the task be executed in a given later time.

i didnt make a PR cos i didnt want to destroy your anyway awesome codes, and this mod was just because of reasons.

(reasons = the password that decrypts user_data content cannot be ina text file near user_data folder)

**Comment by erichlotto** [comment]
That's a good point and I guess I should have taken this path from the beginning, maybe passing the password as an argument, so we don't keep the password written in a text file. That said, auto compounding should be right around the corner, I don't think I'll put any more efforts into this script besides fixing what yieldly team might break by changing their website... Thanks for your suggestion tho 😁

**Comment by ctubio** [comment]
:koala: thanks for your awesome codes'¡

just a note, arguments can be seen during the whole execution of the app while inspecting the current processes running on the machine (user input is the only 100% secret input)
