### ISSUE TITLE
Runs fine in windows 10, but not in ubuntu 20.04

### ISSUE THREAD

**Issue by majestique** [erichlotto/yieldly-compounder#5]
I can run this script fine in windows 10, but in ubuntu 20.04, I'm getting this error:
`(node:60176) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined`

![image](https://user-images.githubusercontent.com/19336285/145919720-b1de6577-4e03-4d76-9896-bab644cc9d9c.png)

My setting: 
![image](https://user-images.githubusercontent.com/19336285/145919805-bb23764f-b16a-47df-aad9-1d835ebe7e2b.png)

I ran the package install in the referenced link in readme:
`sudo apt-get install xvfb libnss3 libatk1.0-0 libatk-bridge2.0-0 libxcomposite1 libcups2 libxrandr2 libpangocairo-1.0-0 libgtk-3-0 -y`

**Question**: Is your desktop unbuntu as well? Is creating the `user_data` under ubuntu desktop required?

I'm thinking perhaps, creating `user_data` folder in windows 10 and then copying it over to ubuntu may be problematic.

**Comment by majestique** [comment]
Adding `args: ['--no-sandbox']` fixed the issue

**Comment by erichlotto** [comment]
Yes, I'm using Ubuntu. I don't need `--no-sandbox`, but glad you got it working :)
